name: 'Brave Build Stage'
description: 'Multi-stage Brave browser build action with platform support'
author: 'Brave Build Team'

inputs:
  finished:
    description: 'If a previous stage already finished the build, skip execution'
    required: true
    default: 'false'
  from_artifact:
    description: 'Resume build from previously uploaded checkpoint artifact'
    required: true
    default: 'false'
  platform:
    description: 'Target platform (linux, macos, windows)'
    required: false
    default: 'linux'
  arch:
    description: 'Target architecture (x64, arm64)'
    required: false
    default: 'x64'
  build_type:
    description: 'Build type (Component or Release)'
    required: false
    default: 'Component'
  env_config:
    description: '.env configuration content for brave-core'
    required: false
    default: ''

outputs:
  finished:
    description: 'Whether the build has finished successfully'

runs:
  using: 'node20'
  main: 'src/main.js'

