name: 'Cleanup Disk'
description: 'Free up disk space by removing unnecessary tools and packages (multi-platform)'
inputs:
  platform:
    description: 'Target platform (linux, macos, windows)'
    required: false
    default: 'linux'
runs:
  using: 'node20'
  main: 'src/main.js'
