name: Build Brave Browser (Linux)
on:  
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup Cleanup Disk Action
        run: npm install
        working-directory: ./.github/actions/cleanup-disk
      - name: Cleanup Disk
        uses: ./.github/actions/cleanup-disk
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: false
          from_artifact: false
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-2:
    needs: build-1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup Cleanup Disk Action
        run: npm install
        working-directory: ./.github/actions/cleanup-disk
      - name: Cleanup Disk
        uses: ./.github/actions/cleanup-disk
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-1.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-3:
    needs: build-2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup Cleanup Disk Action
        run: npm install
        working-directory: ./.github/actions/cleanup-disk
      - name: Cleanup Disk
        uses: ./.github/actions/cleanup-disk
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-2.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-4:
    needs: build-3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup Cleanup Disk Action
        run: npm install
        working-directory: ./.github/actions/cleanup-disk
      - name: Cleanup Disk
        uses: ./.github/actions/cleanup-disk
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-3.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-5:
    needs: build-4
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup Cleanup Disk Action
        run: npm install
        working-directory: ./.github/actions/cleanup-disk
      - name: Cleanup Disk
        uses: ./.github/actions/cleanup-disk
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-4.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  build-6:
    needs: build-5
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup Cleanup Disk Action
        run: npm install
        working-directory: ./.github/actions/cleanup-disk
      - name: Cleanup Disk
        uses: ./.github/actions/cleanup-disk
      - name: Setup Stage
        run: npm install
        working-directory: ./.github/actions/stage
      - name: Run Stage
        id: stage
        uses: ./.github/actions/stage
        with:
          finished: ${{ needs.build-5.outputs.finished }}
          from_artifact: true
    outputs:
      finished: ${{ steps.stage.outputs.finished }}

  publish-release:
    needs: build-6
    runs-on: ubuntu-latest
    steps:
      - name: Download package
        uses: actions/download-artifact@v4
        with:
          name: brave-browser-linux
      - name: Publish release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            brave-browser-*.tar.xz

